### ISSUE TITLE
Stats going offline for ~12mn everyday

### ISSUE THREAD

**Issue by rgaudin** [kiwix/k8s#8]
Uptime robot reports a daily downtime of about 12mn around 4am everyday. It is reported as a ConnectionTimeout.
Pods were running.

It seems to match the end of the matomo-db backup cron job.

**Comment by rgaudin** [comment]
I've moved the cronjob one hour later ; if the downtime happens around 5am, we'll know it's connected

**Comment by kelson42** [comment]
Actually last night it still went down many times.

**Comment by kelson42** [comment]
Once we have fixed the problem, I wonder if we could backup Matomo only once a week. Seems good enough to me.

**Comment by rgaudin** [comment]
Agrees ; we should also make sure that other periodic tasks are not colliding with the backup so that it doesn't suffer any additional stress.

Here's what we currently have:

```
0 2 * * * backup # mysqldump mostly
5 * * * * matomo-archive # lots of read/write ops from what I understand
```

When would be the best window for the weekly backup?

**Comment by kelson42** [comment]
@rgaudin no clue, up to yoy

**Comment by rgaudin** [comment]
OK, when's the best time for service to be disturbed? Europe Saturday to Sunday night?

**Comment by rgaudin** [comment]
Fixed

**Comment by kelson42** [comment]
@rgaudin It still get down once a week, right? It  is not fixed IMO.

**Comment by rgaudin** [comment]
Resstoring archive during the backup brought back a few minutes of downtime. Confirms that both are exclusive. Will adjust the archive schedule.

**Comment by kelson42** [comment]
Went down this morning: Event timestamp: 2022-05-02 04:19:39 UTC+0

**Comment by rgaudin** [comment]
Yes, I know, we've discussed this last Monday. Couldn't find time to work on it before the next occurrence (every monday morning)

**Comment by kelson42** [comment]
Is that still a valid bug? If I look to uptime robot, Stats.kiwix.org are not perfectly stable but this seems to follow a very different pattern!

**Comment by rgaudin** [comment]
It's the same pattern ; uptime robot times out for about 4mn on early sunday morning during the archive (compiling week/month/etc) I think.
It's not systematic though ; probably depends on the quantity of data and resource pressure.

Very hard to debug and has limited impact, hence the stale status

**Comment by rgaudin** [comment]
Closing due to lack of impact… and the fact that we haven't seen it for months
